# Uncomment this line to define a global platform for your project
platform :ios, '8.3'

target 'TalkEventDemoApp-objc' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.3'
  pod 'TalkEventSDK', :path => "./../ios-sdk"
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         config.build_settings['ENABLE_BITCODE'] = 'NO'
         # config.build_settings['EMBEDDED_CONTENT_CONTAINS_SWIFT'] = 'YES'
       end
   end
end
